schema_version = "1.0.0"

id = "additional_batch_rename"
name = "Additional Batch Rename"
tagline = "Additional batch rename operators"
version = "1.0.0"
maintainer = "Endertainer007 <endertainer@protonmail.com>"
type = "add-on"
blender_version_min = "4.4.0"
license = ["SPDX:GPL-3.0-or-later"]